### ISSUE TITLE
Nested structs are flattened

### ISSUE THREAD

**Issue by abeMedia** [dougblack/sleepy#28]
For some reason nested structs are being flattened. I have the following struct
```go
type Data struct {
    Hello string
    World
}

type World struct {
    Foo, Bar int
}
```
And yet it's being displayed like this:
```json
{ 
  "Hello": "hello", 
  "Foo": 0, 
  "Bar": 1
}
```

**Comment by michaeltighe** [comment]
This is the default behavior of marshaling structs to json.  Adding a field tag so the World value gets a proper name should solve your issue though.

    type Data struct {
	    Hello string
	    World `json:"World"`
    }

    type World struct {
    	Foo, Bar int
    }

output:

    {
      "Hello":"hi",
      "World": {
        "Foo":1,
        "Bar":2
      }
    }

**Comment by abeMedia** [comment]
Sorry, I'm a newbie to Go. Thanks a lot for your help!
